### PR TITLE
chore: setup SQL review CI for Bytebase

### PR DESCRIPTION
**Pull request by Francois-Werbrouck**
This pull request is auto-generated by Bytebase for GitOps workflow.

### CODE REVIEW

**Comment by SonOfLope** [comment]
Updated to call a reusable workflow once this PR is merged : https://github.com/ai-cfia/github-workflows/pull/114

**Comment by SonOfLope** [comment]
fyi theres no checks because current state of PR makes the workflow invalid since its pointing to the reussable workflow that hasnt been merged yet (so it resolves into an error of inexistant workflow)

**Comment by rngadam** [comment]
> fyi theres no checks because current state of PR makes the workflow invalid since its pointing to the reussable workflow that hasnt been merged yet (so it resolves into an error of inexistant workflow)

how we typically handle this is first set it to the branch. we always want to test first workflows so we shouldn't make it a requirement that the new workflow be on main before we use it.

**Comment by SonOfLope** [comment]
> > fyi theres no checks because current state of PR makes the workflow invalid since its pointing to the reussable workflow that hasnt been merged yet (so it resolves into an error of inexistant workflow)
> 
> how we typically handle this is first set it to the branch. we always want to test first workflows so we shouldn't make it a requirement that the new workflow be on main before we use it.

Acknowledged. The workflow itself has been tested before doing the changes with a reusable workflow. Here is an example of pointing to a branch to handle typical usecase : 
https://github.com/ai-cfia/dev-rel-docs/pull/123

Current workflow is not a typical situation.

**Review by rngadam — APPROVED** [review]

**Pull request merged**
